"""
Minimal KrutiDev/Chanakya glyph mapping starter.
Extend this mapping for production-grade conversion.
"""

KRUTIDEV_MAPPING = {
    "¼": "ऋ",
    "¶": "ऌ",
    "d": "क",
    "[k": "ख",
    "x": "ग",
    "?": "घ",
    "p": "च",
    "N": "छ",
    "t": "ज",
    "/": "झ",
    "o": "ट",
    "n": "ठ",
    "k": "ा",
    "b": "ि",
    "B": "ी",
    "l": "ु",
    "L": "ू",
    "m": "े",
    "M": "ै",
    "H": "ो",
    "O": "ौ",
    "a": "ं",
    "A": "ँ",
    "%": "ः",
    "0": "०",
    "1": "१",
    "2": "२",
    "3": "३",
    "4": "४",
    "5": "५",
    "6": "६",
    "7": "७",
    "8": "८",
    "9": "९",
}
